import Head from "next/head";
import { Home } from "../components/Home/Home";
import { getPgClient } from "../db";
import { FeatureFlags, Flag, User } from "../helpers/types";

export interface HomeProps {
  users: User[];
}

export default function HomePage({ users }: HomeProps) {
  return (
    <div>
      <Head>
        <title>Labos 2</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home users={users} />
    </div>
  );
}

export async function getServerSideProps() {
  const client = await getPgClient();
  const users = await client.query("SELECT name FROM users");
  const flags = await client.query("SELECT * FROM flags");
  const currentUser = await client.query(
    "SELECT * FROM users WHERE name = 'John'"
  );
  await client.end();

  let featureFlags: FeatureFlags = {};
  flags.rows.forEach((flag: Flag) => {
    featureFlags[flag.name] = flag.isactivated;
  });

  return {
    props: {
      users: users.rows,
      featureFlags,
      currentUser: currentUser.rows[0],
    },
  };
}
